package postgresql

import (
	"database/sql"
	"fmt"
	"goswitch/internal/core"
	"strings"
)

// Metadata PostgreSQL 元数据查询
type Metadata struct {
	db *sql.DB
}

// ListTables 查询表列表
func (m *Metadata) ListTables(database string) ([]string, error) {
	query := "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'"
	rows, err := m.db.Query(query)
	if err != nil {
		return nil, fmt.Errorf("failed to list tables: %w", err)
	}
	defer rows.Close()

	var tables []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, fmt.Errorf("failed to scan table name: %w", err)
		}
		tables = append(tables, name)
	}
	return tables, rows.Err()
}

// GetColumns 查询列信息
func (m *Metadata) GetColumns(database, table string) ([]core.ColumnMeta, error) {
	query := `
		SELECT
			c.column_name,
			c.data_type,
			COALESCE(c.character_maximum_length, 0),
			COALESCE(c.numeric_precision, 0),
			COALESCE(c.numeric_scale, 0),
			c.is_nullable,
			c.column_default,
			COALESCE(pgd.description, ''),
			CASE WHEN c.is_identity = 'YES' THEN true ELSE false END as is_identity
		FROM information_schema.columns c
		LEFT JOIN pg_catalog.pg_statio_all_tables st ON st.relname = c.table_name AND st.schemaname = c.table_schema
		LEFT JOIN pg_catalog.pg_description pgd ON pgd.objoid = st.relid AND pgd.objsubid = c.ordinal_position
		WHERE c.table_schema = 'public' AND c.table_name = $1
		ORDER BY c.ordinal_position`

	rows, err := m.db.Query(query, table)
	if err != nil {
		return nil, fmt.Errorf("failed to get columns: %w", err)
	}
	defer rows.Close()

	var columns []core.ColumnMeta
	for rows.Next() {
		var col core.ColumnMeta
		var nullable string
		var defaultVal sql.NullString
		var isIdentity bool

		err := rows.Scan(
			&col.Name, &col.DataType, &col.Length, &col.Precision, &col.Scale,
			&nullable, &defaultVal, &col.Comment, &isIdentity,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan column: %w", err)
		}

		col.Nullable = nullable == "YES"
		col.AutoIncr = isIdentity || strings.Contains(col.DataType, "serial")
		if defaultVal.Valid {
			col.DefaultValue = &defaultVal.String
		}

		columns = append(columns, col)
	}
	return columns, rows.Err()
}

// GetPrimaryKeys 查询主键
func (m *Metadata) GetPrimaryKeys(database, table string) ([]string, error) {
	query := `
		SELECT column_name
		FROM information_schema.table_constraints tc
		JOIN information_schema.key_column_usage kcu
			ON tc.constraint_name = kcu.constraint_name
			AND tc.table_schema = kcu.table_schema
		WHERE tc.constraint_type = 'PRIMARY KEY'
			AND tc.table_schema = 'public'
			AND tc.table_name = $1
		ORDER BY kcu.ordinal_position`

	rows, err := m.db.Query(query, table)
	if err != nil {
		return nil, fmt.Errorf("failed to get primary keys: %w", err)
	}
	defer rows.Close()

	var keys []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, fmt.Errorf("failed to scan primary key: %w", err)
		}
		keys = append(keys, name)
	}
	return keys, rows.Err()
}

// GenerateCreateTableDDL 生成建表 DDL
func (m *Metadata) GenerateCreateTableDDL(database, table string, columns []core.ColumnMeta, primaryKeys []string) (string, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("CREATE TABLE \"%s\" (\n", table))

	for i, col := range columns {
		sb.WriteString(fmt.Sprintf("  \"%s\" %s", col.Name, m.getFieldDefinition(col)))

		if !col.Nullable {
			sb.WriteString(" NOT NULL")
		}

		if col.DefaultValue != nil {
			sb.WriteString(fmt.Sprintf(" DEFAULT %s", *col.DefaultValue))
		}

		if col.AutoIncr {
			// PostgreSQL 使用 GENERATED BY DEFAULT AS IDENTITY 或 serial
			// 使用 BY DEFAULT 允许手动插入值（数据迁移需要）
			if strings.Contains(col.DataType, "serial") {
				// serial 类型已经自动包含自增
			} else {
				sb.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
			}
		}

		if col.Comment != "" {
			// PostgreSQL 的注释需要单独的 COMMENT ON 语句
		}

		if i < len(columns)-1 || len(primaryKeys) > 0 {
			sb.WriteString(",")
		}
		sb.WriteString("\n")
	}

	if len(primaryKeys) > 0 {
		sb.WriteString(fmt.Sprintf("  PRIMARY KEY (\"%s\")\n", strings.Join(primaryKeys, "\", \"")))
	}

	sb.WriteString(")")

	return sb.String(), nil
}

// getFieldDefinition 获取字段类型定义
// 同时支持 PostgreSQL 原生类型、MySQL 和 Oracle 类型（用于跨数据库迁移）
func (m *Metadata) getFieldDefinition(col core.ColumnMeta) string {
	switch strings.ToLower(col.DataType) {
	// 字符串类型
	case "varchar", "varchar2", "character varying":
		if col.Length > 0 {
			return fmt.Sprintf("varchar(%d)", col.Length)
		}
		return "varchar(255)"
	case "char", "character", "nchar":
		if col.Length > 0 {
			return fmt.Sprintf("char(%d)", col.Length)
		}
		return "char(1)"
	case "nvarchar2":
		if col.Length > 0 {
			return fmt.Sprintf("varchar(%d)", col.Length)
		}
		return "varchar(255)"
	case "text", "tinytext", "mediumtext", "longtext", "clob", "nclob":
		return "text"
	case "enum":
		return "varchar(255)"
	case "set":
		return "text"

	// 数值类型
	case "numeric", "decimal":
		if col.Precision > 0 {
			return fmt.Sprintf("numeric(%d,%d)", col.Precision, col.Scale)
		}
		return "numeric"
	case "number":
		// Oracle NUMBER 类型映射
		if col.Scale > 0 {
			return fmt.Sprintf("numeric(%d,%d)", col.Precision, col.Scale)
		}
		if col.Precision <= 10 {
			return "integer"
		}
		if col.Precision <= 19 {
			return "bigint"
		}
		return "bigint"
	case "integer", "int", "int4":
		return "integer"
	case "bigint", "int8":
		return "bigint"
	case "smallint", "int2":
		return "smallint"
	case "tinyint":
		if col.Length == 1 {
			return "boolean"
		}
		return "smallint"
	case "mediumint":
		return "integer"
	case "float", "real", "float4", "binary_float":
		return "real"
	case "double", "double precision", "float8", "binary_double":
		return "double precision"
	case "boolean", "bool":
		return "boolean"

	// 日期时间类型
	case "datetime":
		return "timestamp"
	case "timestamp", "timestamp without time zone":
		return "timestamp"
	case "timestamp with time zone", "timestamptz":
		return "timestamptz"
	case "date":
		return "timestamp" // Oracle DATE 包含时间
	case "time", "time without time zone":
		return "time"
	case "year":
		return "integer"

	// 二进制类型
	case "blob", "tinyblob", "mediumblob", "longblob", "binary", "varbinary", "raw":
		return "bytea"
	case "bytea":
		return "bytea"

	// JSON 类型
	case "json":
		return "json"
	case "jsonb":
		return "jsonb"

	// UUID
	case "uuid":
		return "uuid"

	// MongoDB 类型
	case "objectid":
		return "varchar(24)"
	case "document":
		return "jsonb"
	case "array":
		return "jsonb"
	case "long":
		return "bigint"
	case "decimal128":
		return "numeric"
	case "null":
		return "text"

	default:
		// 未知类型尝试直接使用
		return col.DataType
	}
}